site_name: DeepLens
site_description: A library for mechanistic interpretability research
site_author: IÃ±igo Parra
repo_url: https://github.com/iparramartin/deeplens
repo_name: deeplens

theme:
  name: material
  logo: assets/logo_nb.png
  favicon: assets/logo_nb.png
  palette:
    - scheme: slate
      primary: deep blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      
    - scheme: default
      primary: deep blue
      accent: blue
      toggle:
        icon: material/brightness-3
        name: Switch to dark mode
  
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate
  
  icon:
    repo: fontawesome/brands/github
  

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
  - pymdownx.arithmatex:
      generic: true
  
  - admonition
  - pymdownx.details
  
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

# Navigation structure
nav:
  - Home: index.md
  - Introduction:
    - Getting Started: getting-started.md
    - Installation: installation.md
    - Quick Start: quickstart.md
  - Tutorials:
    - Feature Extraction: tutorials/extraction.md
    - Dataset Setup: tutorials/dataset.md
    - Training SAEs: tutorials/sae.md
    - Feature Interventions: tutorials/interventions.md
    - Analysis: tutorials/analysis.md
  - API Reference:
    - Core API: api/core.md
    - Utils: api/utils.md
  - Resources:
    - Examples: examples.md

# Footer links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iparramartin
    - icon: fontawesome/brands/twitter
      link: https://x.com/IParraMartin

# Plugins
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [deeplens]
          options:
            show_source: true
            show_root_heading: true